create table Users
(
    ID      INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME    CHARACTER VARYING(255),
    CREATED TIMESTAMP default CURRENT_TIMESTAMP
);
create table Roles
(
    ID      INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME    CHARACTER VARYING(255)
);
