version: 2
updates:
  - package-ecosystem: "maven" 
    directory: "/" 
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 20
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
