CREATE TABLE User (
  id      INT IDENTITY PRIMARY KEY,
  name    VARCHAR(255),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Role (
  id  INT IDENTITY PRIMARY KEY,
  name VARCHAR(255)
);