CREATE TABLE ${schema}.Users (
  id      INT IDENTITY PRIMARY KEY,
  name    VARCHAR(255),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE ${schema}.Roles (
  id  INT IDENTITY PRIMARY KEY,
  name VARCHAR(255)
);